-- =============================================================================
-- Auto-create team on user signup
-- =============================================================================
-- This trigger automatically creates a team for new users when they sign up
-- Team name: "{FirstName}'s Team"
-- Team slug: Auto-generated by Supabase's generate_team_slug function

-- Function to generate a clean slug from team name (with uniqueness check)
CREATE OR REPLACE FUNCTION generate_team_slug(team_name TEXT)
RETURNS TEXT AS $$
DECLARE
    base_slug TEXT;
    final_slug TEXT;
    counter INTEGER := 1;
BEGIN
    -- Convert to lowercase and replace spaces/special chars with hyphens
    base_slug := lower(regexp_replace(team_name, '[^a-zA-Z0-9\s]', '', 'g'));
    base_slug := regexp_replace(base_slug, '\s+', '-', 'g');
    
    -- Remove leading/trailing hyphens
    base_slug := trim(both '-' from base_slug);
    
    -- Start with base slug
    final_slug := base_slug;
    
    -- Keep trying until we find a unique slug
    WHILE EXISTS (
        SELECT 1 FROM public.teams WHERE slug = final_slug
    ) LOOP
        final_slug := base_slug || '-' || counter;
        counter := counter + 1;
    END LOOP;
    
    RETURN final_slug;
END;
$$ LANGUAGE plpgsql;

-- Function to create team for new user
CREATE OR REPLACE FUNCTION create_team_for_new_user()
RETURNS TRIGGER 
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  first_name TEXT;
  team_name TEXT;
  team_id UUID;
BEGIN
  -- Extract first name from user metadata
  first_name := COALESCE(
    NEW.raw_user_meta_data->>'first_name',
    split_part(NEW.email, '@', 1)  -- Fallback to email prefix if no first name
  );

  -- Generate team name
  IF first_name ~* 's$' THEN
    -- Names ending in 's' (e.g., "James" -> "James' Team")
    team_name := first_name || ''' Team';
  ELSE
    -- Regular names (e.g., "Tom" -> "Tom's Team")
    team_name := first_name || '''s Team';
  END IF;

  -- Create team (slug will be auto-generated by trigger)
  INSERT INTO teams (id, name, description)
  VALUES (gen_random_uuid(), team_name, 'Personal team for ' || first_name)
  RETURNING id INTO team_id;

  -- Create team membership (user as owner)
  INSERT INTO team_memberships (id, user_id, team_id, role, is_owner)
  VALUES (
    gen_random_uuid(),
    NEW.id,
    team_id,
    'owner',
    TRUE
  );

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to run on user creation
CREATE TRIGGER trigger_create_team_on_signup
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION create_team_for_new_user();

-- Grant necessary permissions for the trigger function
-- The function runs as SECURITY DEFINER, so it needs explicit grants
GRANT USAGE ON SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT INSERT, SELECT ON public.teams TO postgres, service_role;
GRANT INSERT, SELECT ON public.team_memberships TO postgres, service_role;

-- Trigger function to automatically set slug on team creation
CREATE OR REPLACE FUNCTION set_team_slug_trigger()
RETURNS TRIGGER AS $$
BEGIN
    -- Only set slug if it's not already provided
    IF NEW.slug IS NULL OR NEW.slug = '' THEN
        NEW.slug := generate_team_slug(NEW.name);
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create the trigger on the teams table
DROP TRIGGER IF EXISTS team_slug_trigger ON teams;
CREATE TRIGGER team_slug_trigger
    BEFORE INSERT OR UPDATE ON teams
    FOR EACH ROW
    EXECUTE FUNCTION set_team_slug_trigger();

-- Grant necessary permissions
GRANT EXECUTE ON FUNCTION generate_team_slug(TEXT) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION set_team_slug_trigger() TO authenticated, service_role;

-- Comment for documentation
COMMENT ON FUNCTION create_team_for_new_user() IS 'Automatically creates a team and team membership for new users on signup';
COMMENT ON FUNCTION generate_team_slug(TEXT) IS 'Generates URL-friendly slug from team name with uniqueness check';
COMMENT ON FUNCTION set_team_slug_trigger() IS 'Trigger function that auto-generates slug for teams if not provided';

